# Generated by Django 3.1.7 on 2021-04-03 07:12

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCovid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('about_covid_19', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'About COVID-19',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('uploaded_date', models.DateField()),
                ('location', models.CharField(default='Morogoro', max_length=50)),
                ('image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Blogs List',
            },
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('call_document', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Calls List',
            },
        ),
        migrations.CreateModel(
            name='CED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('left_description', ckeditor.fields.RichTextField()),
                ('headline', models.CharField(max_length=200)),
                ('left_headline', models.CharField(max_length=200)),
                ('image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('document', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('left_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Chief Executive Director',
            },
        ),
        migrations.CreateModel(
            name='CollaboratingInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Collaborating Institutions',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Customer contact list',
            },
        ),
        migrations.CreateModel(
            name='Covid19Guidlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('covid_19Guidlines', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'COVID-19 Guidlines',
            },
        ),
        migrations.CreateModel(
            name='Covid19HowToStaySafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('covid_19HowToStaySafe', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'COVID-19 How to stay safe',
            },
        ),
        migrations.CreateModel(
            name='Covid19Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('covid_19Notice', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'COVID-19 notice',
            },
        ),
        migrations.CreateModel(
            name='Covid19Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('covid_19Stats', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'COVID-19 Stats',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('caption', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(max_length=20)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='Morogoro', max_length=50)),
                ('image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Events Lists',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'FAQs list',
            },
        ),
        migrations.CreateModel(
            name='FunndingPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Funnding Partners',
            },
        ),
        migrations.CreateModel(
            name='Governance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(default='Director', max_length=100)),
                ('headline', models.CharField(default='', max_length=1000)),
                ('governance', models.CharField(choices=[('', 'select governance'), ('BOG', 'Board of Governors'), ('BOT', 'Board of Trustees'), ('MC', 'Management Committee'), ('SAC', 'Scientific Advisory Committee'), ('FARC', 'Finance, Audit and Risk Committee')], default='MC', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('publication_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Governance List',
            },
        ),
        migrations.CreateModel(
            name='InnovationHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Innovation-hub',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('job_document', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Jobs List',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('caption', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('location', models.CharField(default='Morogoro', max_length=50)),
                ('image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('video_file', models.URLField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'News List',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('opportunity_document', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Opportunity List',
            },
        ),
        migrations.CreateModel(
            name='PolicyBriefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('pdf_document', models.FileField(upload_to='')),
                ('photo', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Policy Briefs List',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('project_leader', models.CharField(blank=True, max_length=100)),
                ('principal_investigator', models.CharField(blank=True, max_length=100)),
                ('administrator', models.CharField(blank=True, max_length=100)),
                ('funding_partner', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(choices=[('', 'select department'), ('EH', 'Environmental Health and Ecological Sciences'), ('IC', 'Interventions and Clinical Trials'), ('HS', 'Health Systems, Impact Evaluation and Policy'), ('TC', 'Training & Capacity Building')], max_length=50)),
                ('image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Projects List',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=500)),
                ('journal_name', models.CharField(max_length=100)),
                ('authors', models.CharField(default='', max_length=1000)),
                ('website_link', models.CharField(max_length=200)),
                ('abstract', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Publications List',
            },
        ),
        migrations.CreateModel(
            name='SiteVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Website video list',
            },
        ),
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('pdf_document', models.FileField(upload_to='')),
                ('photo', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Spotlights List',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('profile_image', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('headline', models.CharField(default='', max_length=1000)),
                ('environmental_department', models.CharField(blank=True, choices=[('', 'select department'), ('EH', 'Environmental Health and Ecological Sciences'), ('IC', 'Interventions and Clinical Trials'), ('HS', 'Health Systems, Impact Evaluation and Policy'), ('TC', 'Training & Capacity Building')], default='select department', max_length=50)),
                ('intervention_department', models.CharField(blank=True, choices=[('', 'select department'), ('EH', 'Environmental Health and Ecological Sciences'), ('IC', 'Interventions and Clinical Trials'), ('HS', 'Health Systems, Impact Evaluation and Policy'), ('TC', 'Training & Capacity Building')], default='select department', max_length=50)),
                ('health_department', models.CharField(blank=True, choices=[('', 'select department'), ('EH', 'Environmental Health and Ecological Sciences'), ('IC', 'Interventions and Clinical Trials'), ('HS', 'Health Systems, Impact Evaluation and Policy'), ('TC', 'Training & Capacity Building')], default='select department', max_length=50)),
                ('directorate', models.CharField(blank=True, choices=[('', 'select directorate'), ('RQA', 'Research Quality Assurance'), ('IRB', 'Institutional Review Board'), ('KMC', 'Knowledge Management and Communications')], default='select directorate', max_length=50)),
                ('units', models.CharField(blank=True, choices=[('', 'select units'), ('IA', 'Internal Audit'), ('FM', 'Finance Management'), ('HRM', 'Human Resources Management'), ('PM', 'Procurement Management'), ('BA', 'Branch Administration'), ('ICT', 'ICT unit'), ('GC', 'Grants and Contracts'), ('TCB', 'Training and Capacity Building'), ('LAB', 'Laboratories'), ('DSP', 'Data Systems and Platforms'), ('CT', 'Clinical Trials'), ('CDCIM', 'Chronic Diseases Clinic in Ifakara and Mwananyamala'), ('TRANSPORT', 'Transport'), ('IH', 'Ifakara Hub')], default='select units', max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('background_and_education', ckeditor.fields.RichTextField()),
                ('professional_experience_and_skills', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('publication_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Staffs List',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Subscriber list',
            },
        ),
    ]
