# Generated by Django 2.2.3 on 2019-08-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Calls',
        ),
        migrations.DeleteModel(
            name='CED',
        ),
        migrations.DeleteModel(
            name='CollaboratingInstitutions',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='FunndingPartners',
        ),
        migrations.DeleteModel(
            name='Governance',
        ),
        migrations.DeleteModel(
            name='InnovationHub',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
