# Generated by Django 3.1.7 on 2021-04-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0002_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
