# Generated by Django 2.1.15 on 2021-04-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0003_remove_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='calls',
            options={'verbose_name_plural': 'Calls'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Customer contact '},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='governance',
            options={'verbose_name_plural': 'Governance'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunity'},
        ),
        migrations.AlterModelOptions(
            name='policybriefs',
            options={'verbose_name_plural': 'Policy Briefs'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='sitevideo',
            options={'verbose_name_plural': 'Website video '},
        ),
        migrations.AlterModelOptions(
            name='spotlight',
            options={'verbose_name_plural': 'Spotlights'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Subscriber '},
        ),
        migrations.AddField(
            model_name='jobs',
            name='uploaded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
