# Generated by Django 3.1 on 2021-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0004_auto_20210430_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='governance',
            name='order_of_preference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='units',
            field=models.CharField(blank=True, choices=[('', 'select units'), ('IA', 'Internal Audit'), ('FM', 'Finance Management'), ('HRM', 'Human Resources Management'), ('PM', 'Procurement Management'), ('BA', 'Branch Administration'), ('ICT', 'ICT unit'), ('GC', 'Grants and Contracts'), ('TCB', 'Training and Capacity Building'), ('LAB', 'Laboratories'), ('DSP', 'Data Systems and Platforms'), ('CT', 'Clinical Trials'), ('CDCIM', 'Chronic Diseases Clinic in Ifakara and Mwananyamala'), ('TRANSPORT', 'Transport'), ('IH', 'Ifakara Hub'), ('RQA', 'Research Quality Assurance'), ('VCPTU', 'Vector Control Product Testing Unit'), ('KMC', 'Knowledge Management and Communications')], default='select units', max_length=50),
        ),
    ]
