# Generated by Django 2.2.3 on 2019-09-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0004_auto_20190823_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyBriefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('pdf_document', models.FileField(upload_to='')),
                ('photo', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Policy Briefs List',
            },
        ),
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('pdf_document', models.FileField(upload_to='')),
                ('photo', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Spotlights List',
            },
        ),
        migrations.AddField(
            model_name='governance',
            name='position',
            field=models.CharField(default='Director', max_length=100),
        ),
    ]
