# Generated by Django 2.2.3 on 2019-10-04 07:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0005_auto_20190927_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='calls',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ced',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ced',
            name='left_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='governance',
            name='background_and_education',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='governance',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='governance',
            name='professional_experience_and_skills',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='innovationhub',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='policybriefs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publications',
            name='abstract',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='background_and_education',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='professional_experience_and_skills',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
