# Generated by Django 2.2.3 on 2020-04-04 12:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0006_auto_20191004_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCovid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('about_covid_19', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'About COVID-19',
            },
        ),
        migrations.CreateModel(
            name='Covid19Guidlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('covid_19Guidlines', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'COVID-19 Guidlines',
            },
        ),
        migrations.CreateModel(
            name='Covid19HowToStaySafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('covid_19HowToStaySafe', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'COVID-19 How to stay safe',
            },
        ),
        migrations.CreateModel(
            name='Covid19Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('covid_19Notice', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'COVID-19 notice',
            },
        ),
        migrations.CreateModel(
            name='Covid19Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('covid_19HowToStaySafe', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'COVID-19 Stats',
            },
        ),
    ]
