# Generated by Django 2.1.15 on 2020-11-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0009_auto_20201118_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governance',
            name='background_and_education',
        ),
        migrations.RemoveField(
            model_name='governance',
            name='governance1',
        ),
        migrations.RemoveField(
            model_name='governance',
            name='professional_experience_and_skills',
        ),
        migrations.RemoveField(
            model_name='governance',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='governance',
            name='governance',
            field=models.CharField(choices=[('', 'select governance'), ('BOG', 'Board of Governors'), ('BOT', 'Board of Trustees'), ('MC', 'Management Committee'), ('SAC', 'Scientific Advisory Committee'), ('FARC', 'Finance, Audit and Risk Committee')], default='MC', max_length=50),
        ),
    ]
