# Generated by Django 2.1.15 on 2020-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Website video list',
            },
        ),
    ]
