# Generated by Django 2.1.15 on 2020-11-28 08:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0013_sitevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19stats',
            name='covid_19Stats',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
