# Generated by Django 2.1.15 on 2020-11-28 09:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0014_auto_20201128_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
