# Generated by Django 2.1.15 on 2020-12-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0019_auto_20201204_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
