# Generated by Django 2.1.15 on 2020-12-04 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0020_remove_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
