# Generated by Django 2.1.15 on 2020-12-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihi_wepapp', '0021_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=500, unique_for_date='created'),
        ),
    ]
